import type { SpotifyGenresForMarket } from '../types/types';

export const top50genres_exampleData: SpotifyGenresForMarket[] = [
	{
		countryName: 'Australia',
		genres: [
			{ genre: 'pop', count: 14 },
			{ genre: 'rap', count: 9 },
			{ genre: 'hip hop', count: 5 },
			{ genre: 'dance pop', count: 5 },
			{ genre: 'r&b', count: 4 },
			{ genre: 'singer-songwriter pop', count: 3 },
			{ genre: 'pov: indie', count: 3 },
			{ genre: 'pop rap', count: 3 },
			{ genre: 'atl hip hop', count: 3 },
			{ genre: 'trap', count: 2 },
			{ genre: 'plugg', count: 2 },
			{ genre: 'kentucky hip hop', count: 2 },
			{ genre: 'contemporary country', count: 2 },
			{ genre: 'uk pop', count: 2 },
			{ genre: 'house', count: 2 },
			{ genre: 'canadian pop', count: 2 },
			{ genre: 'chicago rap', count: 1 },
			{ genre: 'southern hip hop', count: 1 },
			{ genre: 'trap soul', count: 1 },
			{ genre: 'melodic rap', count: 1 },
			{ genre: 'pluggnb', count: 1 },
			{ genre: 'rage rap', count: 1 },
			{ genre: 'alt z', count: 1 },
			{ genre: 'indie pop', count: 1 },
			{ genre: 'psychedelic pop', count: 1 },
			{ genre: 'deep underground hip hop', count: 1 },
			{ genre: 'classic oklahoma country', count: 1 },
			{ genre: 'classic texas country', count: 1 },
			{ genre: 'country dawn', count: 1 },
			{ genre: 'hypertechno', count: 1 },
			{ genre: 'uk contemporary r&b', count: 1 },
			{ genre: 'melodic drill', count: 1 },
			{ genre: 'uk hip hop', count: 1 },
			{ genre: 'edm', count: 1 },
			{ genre: 'stutter house', count: 1 },
			{ genre: 'post-teen pop', count: 1 },
			{ genre: 'australian house', count: 1 },
			{ genre: 'deep groove house', count: 1 },
			{ genre: 'canadian contemporary r&b', count: 1 },
			{ genre: 'k-pop', count: 1 },
			{ genre: 'british singer-songwriter', count: 1 },
			{ genre: 'folk-pop', count: 1 },
			{ genre: 'modern rock', count: 1 },
			{ genre: 'canadian hip hop', count: 1 },
			{ genre: 'trap queen', count: 1 },
			{ genre: 'gen z singer-songwriter', count: 1 },
			{ genre: 'viral rap', count: 1 },
			{ genre: 'indie folk', count: 1 },
			{ genre: 'stomp and holler', count: 1 },
			{ genre: 'europop', count: 1 },
			{ genre: 'new wave pop', count: 1 },
			{ genre: 'brooklyn indie', count: 1 },
			{ genre: 'experimental r&b', count: 1 }
		]
	}
];
